//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToClients
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user
    {
        public string phonenumber { get; set; }
        public string gcmregistrationid { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string devicetype { get; set; }
        public Nullable<int> appversioncode { get; set; }
        public string statetext { get; set; }
        public string waitings { get; set; }
        public Nullable<int> fullstate { get; set; }
        public Nullable<System.DateTime> reconnectpushdate { get; set; }
        public string timezone { get; set; }
        public bool isuninstalled { get; set; }
        public string uninstallationreason { get; set; }
    }
}
