//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppleFeedback
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public System.DateTime AppleDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Enviroment { get; set; }
    }
}
