//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Property
    {
        public int ID { get; set; }
        public int propertyID { get; set; }
        public int businessID { get; set; }
        public string url { get; set; }
        public int Sort { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Property Property { get; set; }
    }
}
