//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Activity
    {
        public int ID { get; set; }
        public int businessID { get; set; }
        public string area { get; set; }
        public string type { get; set; }
        public string starthours { get; set; }
        public int days { get; set; }
        public string endhours { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
