//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Communication
    {
        public int ID { get; set; }
        public int businessID { get; set; }
        public int comunicationID { get; set; }
        public int Sort { get; set; }
        public string linkContent { get; set; }
        public int availableID { get; set; }
    
        public virtual AvailabilityType AvailabilityType { get; set; }
        public virtual Business Business { get; set; }
        public virtual Communication Communication { get; set; }
    }
}
