//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUpdated
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> FullState { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> TextUpdateDate { get; set; }
        public Nullable<System.DateTime> StateAvailabilityDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
