//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrunchesLog
    {
        public int Id { get; set; }
        public string CruncherPhone { get; set; }
        public string DestinationPhone { get; set; }
        public int Action { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
