//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mystateApiDbEntities1 : DbContext
    {
        public mystateApiDbEntities1()
            : base("name=mystateApiDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AvailabilityType> AvailabilityTypes { get; set; }
        public virtual DbSet<Business_Activity> Business_Activity { get; set; }
        public virtual DbSet<Business_Communication> Business_Communication { get; set; }
        public virtual DbSet<Business_Property> Business_Property { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<CommunicationType> CommunicationTypes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<AccessTokensLog> AccessTokensLogs { get; set; }
        public virtual DbSet<AlphaList> AlphaLists { get; set; }
        public virtual DbSet<AnalyticsKey> AnalyticsKeys { get; set; }
        public virtual DbSet<AppleFeedback> AppleFeedbacks { get; set; }
        public virtual DbSet<BlackList> BlackLists { get; set; }
        public virtual DbSet<CompanyPhone> CompanyPhones { get; set; }
        public virtual DbSet<ContactStateWasInterested> ContactStateWasInteresteds { get; set; }
        public virtual DbSet<ContactUpdated> ContactUpdateds { get; set; }
        public virtual DbSet<CrunchesLog> CrunchesLogs { get; set; }
        public virtual DbSet<DailyNonMyStateContact> DailyNonMyStateContacts { get; set; }
        public virtual DbSet<InstallationsLog> InstallationsLogs { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MyMyStateContact> MyMyStateContacts { get; set; }
        public virtual DbSet<NonMystateContact> NonMystateContacts { get; set; }
        public virtual DbSet<NonMyStateContactsAggregation> NonMyStateContactsAggregations { get; set; }
        public virtual DbSet<NonMyStateContactsForMarketing> NonMyStateContactsForMarketings { get; set; }
        public virtual DbSet<PendingVerification> PendingVerifications { get; set; }
        public virtual DbSet<PushRespons> PushResponses { get; set; }
        public virtual DbSet<ServerPushCode> ServerPushCodes { get; set; }
        public virtual DbSet<ShareCode> ShareCodes { get; set; }
        public virtual DbSet<SmsLog> SmsLogs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<GArea> GAreas { get; set; }
        public virtual DbSet<NonMyStateContactsForMarketingTemp> NonMyStateContactsForMarketingTemps { get; set; }
        public virtual DbSet<vw_clean_uninstall> vw_clean_uninstall { get; set; }
        public virtual DbSet<vw_friends_days_uninstall_basic> vw_friends_days_uninstall_basic { get; set; }
        public virtual DbSet<vw_friends_days_uninstall_basic_Israel> vw_friends_days_uninstall_basic_Israel { get; set; }
        public virtual DbSet<vw_ghost_users_full_data> vw_ghost_users_full_data { get; set; }
        public virtual DbSet<vw_gohst_users> vw_gohst_users { get; set; }
        public virtual DbSet<vw_mystate_friends> vw_mystate_friends { get; set; }
        public virtual DbSet<vw_mystate_friends_created_date> vw_mystate_friends_created_date { get; set; }
        public virtual DbSet<vw_mystate_friends_when_install> vw_mystate_friends_when_install { get; set; }
        public virtual DbSet<vw_mystate_friends_with_create_date_to_all> vw_mystate_friends_with_create_date_to_all { get; set; }
        public virtual DbSet<vw_TablesSize> vw_TablesSize { get; set; }
        public virtual DbSet<vw_uninstall> vw_uninstall { get; set; }
        public virtual DbSet<vw_users> vw_users { get; set; }
        public virtual DbSet<vw_without_gsm_users_full_data> vw_without_gsm_users_full_data { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<script_deployment_status> script_deployment_status { get; set; }
        public virtual DbSet<script_deployments> script_deployments { get; set; }
    }
}
