//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonMyStateContactsForMarketing
    {
        public string PhoneNumber { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> TimesContacted { get; set; }
        public Nullable<bool> Starred { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public Nullable<bool> Recents { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
