//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushRespons
    {
        public int Id { get; set; }
        public string Json { get; set; }
        public string Response { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PhoneNumber { get; set; }
    }
}
