//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerPushCode
    {
        public string PhoneNumber { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PushCode { get; set; }
        public bool IsInstalled { get; set; }
        public string UninstallationReason { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
