//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsLog
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public int SmsType { get; set; }
        public string TextSent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SmsResponse { get; set; }
        public string ReceiptStatus { get; set; }
        public string ReceiptErrCcode { get; set; }
    }
}
