//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public string PhoneNumber { get; set; }
        public string StateText { get; set; }
        public Nullable<System.DateTime> StateTextDate { get; set; }
        public Nullable<System.DateTime> StateAvailabilityDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Waitings { get; set; }
        public Nullable<int> FullState { get; set; }
        public int ViewCount { get; set; }
        public Nullable<System.DateTime> ViewCountDate { get; set; }
        public Nullable<System.DateTime> ReconnectPushDate { get; set; }
        public bool IsHideRingerMode { get; set; }
        public bool IsHideManualAvailability { get; set; }
        public bool IsHideBatteryAndCharging { get; set; }
        public string TimeZone { get; set; }
        public bool IsUninstalled { get; set; }
        public string UninstallationReason { get; set; }
    }
}
