//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string perCode { get; set; }
        public bool Status { get; set; }
        public string GcmRegistrationId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeviceType { get; set; }
        public string AccessToken { get; set; }
        public string AppVersion { get; set; }
        public Nullable<int> AppVersionCode { get; set; }
        public string AndroidId { get; set; }
    }
}
