//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_gohst_users
    {
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public Nullable<int> LastSeenDiff { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateDateDiff { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateDateDiff { get; set; }
        public Nullable<int> AppVersionCode { get; set; }
    }
}
