//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mystate_friends_with_create_date_to_all
    {
        public string UserPhone { get; set; }
        public Nullable<System.DateTime> User_CreateDate { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> ContactPhone_CreateDate { get; set; }
    }
}
