//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_uninstall
    {
        public string PhoneNumber { get; set; }
        public System.DateTime install { get; set; }
        public int inAction { get; set; }
        public System.DateTime uninstall { get; set; }
        public int unAction { get; set; }
        public string Reason { get; set; }
        public Nullable<int> diff_days { get; set; }
        public Nullable<int> diff_hours { get; set; }
    }
}
